[dist]
# The preferred cargo-dist version to use in CI (Cargo.toml metadata)
cargo-dist-version = "0.8.0"
# CI backends to support
ci = ["github"]
# The installers to generate for each app
installers = ["shell", "powershell", "msi"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-pc-windows-msvc", "x86_64-unknown-linux-gnu"]
# Publish jobs to run in CI
publish-jobs = ["github-release"]
# Whether to pass --all-features when building the application
all-features = true

# GitHub releases settings
[dist.github-release]
# CI dependencies we need
extra-artifacts = ["README.md", "LICENSE"]

# Windows MSI installer settings
[dist.msi]
product-name = "Windows MTR"
manufacturer = "Benji Shohet (benjisho)"
license-url = "https://github.com/benjisho/windows-mtr/blob/main/LICENSE"
upgrade-guid = "A7C57969-6052-46AA-BF9F-A5C6AFD79401"
# Add start menu shortcut
create-start-menu-shortcut = true