name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build and Release
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: clippy

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Install trippy and cargo-dist
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: trippy cargo-dist

      - name: Run Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets -- -D warnings

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all

      - name: Build release binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-pc-windows-msvc

      - name: Package distribution
        run: |
          cargo run --package xtask -- dist

      - name: Create MSI installer
        run: |
          cargo dist build --target=x86_64-pc-windows-msvc --installer=msi

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-mtr
          path: |
            dist/
            target/dist/

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
            target/dist/*.msi
          name: Windows MTR v${{ github.ref_name }}
          body: |
            Windows MTR v${{ github.ref_name }} - A Windows-native clone of Linux MTR
            
            ## Installation
            - **ZIP Package**: Extract and run `mtr.exe`
            - **MSI Installer**: Run the installer for a system-wide installation
            
            See [USAGE.md](https://github.com/benjisho/windows-mtr/blob/main/USAGE.md) for detailed usage instructions.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}