name: Workflow QA

on:
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Run actionlint
        uses: rhysd/actionlint@v1
